#!/usr/bin/env ruby
# frozen_string_literal: true

require "cgi"
require "date"
require "pathname"
require "time"
require "yaml"

ROOT = Pathname.new(File.expand_path("..", __dir__))
SITE_URL = "https://brenorb.com"
OUTPUT = ROOT.join("llms-ctx-full.txt")

PAGE_SOURCES = [
  "index.html",
  "about/index.md",
  "articles/index.md",
  "media/index.md",
  "projects/index.md"
].freeze

def load_yaml(text)
  if YAML.respond_to?(:unsafe_load)
    YAML.unsafe_load(text)
  else
    YAML.load(text)
  end
end

def read_source(relative_path)
  path = ROOT.join(relative_path)
  text = path.read

  if text.start_with?("---")
    parts = text.split(/^---\s*$/, 3)
    front_matter = load_yaml(parts[1] || "") || {}
    body = parts[2] || ""
  else
    front_matter = {}
    body = text
  end

  [front_matter, body]
end

def public_source?(front_matter)
  front_matter["published"] != false && front_matter["sitemap"] != false
end

def post_url(relative_path, front_matter)
  permalink = front_matter["permalink"].to_s.strip
  return absolute_url(permalink) unless permalink.empty?

  basename = File.basename(relative_path, ".md")
  slug = basename.sub(/^\d{4}-\d{2}-\d{2}-/, "")
  absolute_url("/#{slug}/")
end

def page_url(relative_path)
  return absolute_url("/") if relative_path == "index.html"

  absolute_url("/#{relative_path.sub(%r{/index\.md$}, "/")}")
end

def absolute_url(path)
  normalized = path.start_with?("/") ? path : "/#{path}"
  "#{SITE_URL}#{normalized}"
end

def normalize_scalar(value)
  case value
  when Date, Time
    value.iso8601
  when Array
    value.map(&:to_s).join(", ")
  when nil
    ""
  else
    value.to_s.strip
  end
end

def clean_body(body)
  text = body.dup

  text.gsub!(%r{<iframe[^>]*src=["']([^"']+)["'][^>]*>.*?</iframe>}im, "\nEmbedded media: \\1\n")
  text.gsub!(%r{<a[^>]*href=["']([^"']+)["'][^>]*>(.*?)</a>}im) do
    href = Regexp.last_match(1).strip
    label = Regexp.last_match(2).gsub(/<[^>]+>/, "").strip
    label.empty? ? href : "#{label} (#{href})"
  end
  text.gsub!(%r{<script.*?</script>}im, "\n")
  text.gsub!(%r{<style.*?</style>}im, "\n")
  text.gsub!(%r{<[^>]+>}, " ")
  text.gsub!(/\{\:\s*[^}]+\}/, "")
  text.gsub!(/\{%\s.*?\s%\}/m, " ")
  text.gsub!(/\{\{\s.*?\s\}\}/m, " ")
  text.gsub!(/\r\n?/, "\n")
  text.gsub!(/[ \t]+/, " ")
  text.gsub!(/\n{3,}/, "\n\n")

  CGI.unescapeHTML(text).strip
end

def emit_entry(lines, title:, url:, source:, front_matter:, body:)
  tags = front_matter["tags"] || front_matter["tag"]
  excerpt = normalize_scalar(front_matter["description"] || front_matter["excerpt"])
  date = normalize_scalar(front_matter["date"])
  content_type = normalize_scalar(front_matter["content_type"])
  cleaned_body = clean_body(body)

  lines << "### #{title}"
  lines << ""
  lines << "URL: #{url}"
  lines << "Source: #{source}"
  lines << "Date: #{date}" unless date.empty?
  lines << "Content type: #{content_type}" unless content_type.empty?
  lines << "Tags: #{normalize_scalar(tags)}" unless normalize_scalar(tags).empty?
  lines << "Summary: #{excerpt}" unless excerpt.empty?
  lines << ""
  lines << cleaned_body unless cleaned_body.empty?
  lines << ""
end

config = load_yaml(ROOT.join("_config.yml").read) || {}

lines = []
lines << "# #{config["title"]} - full public site text"
lines << ""
lines << "This file is generated by `scripts/build-llms-ctx-full.rb`. Do not edit it manually."
lines << ""
lines << "Canonical site: #{config["url"] || SITE_URL}"
lines << "Description: #{config["description"]}"
lines << "Keywords: #{config["keywords"]}"
lines << "AI usage: #{config["ai_use"]}"
lines << ""

lines << "## Public pages"
lines << ""

PAGE_SOURCES.each do |relative_path|
  front_matter, body = read_source(relative_path)
  next unless public_source?(front_matter)

  title = normalize_scalar(front_matter["title"])
  title = config["title"] if title.empty? || title == "Home"

  emit_entry(
    lines,
    title: title,
    url: page_url(relative_path),
    source: relative_path,
    front_matter: front_matter,
    body: body
  )
end

lines << "## Posts, projects, talks, and media"
lines << ""

post_entries = ROOT.join("_posts").children.select { |path| path.extname == ".md" }.filter_map do |path|
  relative_path = path.relative_path_from(ROOT).to_s
  front_matter, body = read_source(relative_path)
  next unless public_source?(front_matter)

  [front_matter["date"] || Date.new(0), relative_path, front_matter, body]
end

post_entries.sort_by { |date, relative_path, _front_matter, _body| [normalize_scalar(date), relative_path] }.reverse_each do |_date, relative_path, front_matter, body|
  title = normalize_scalar(front_matter["title"])
  next if title.empty?

  emit_entry(
    lines,
    title: title,
    url: post_url(relative_path, front_matter),
    source: relative_path,
    front_matter: front_matter,
    body: body
  )
end

OUTPUT.write("#{lines.join("\n").rstrip}\n")
puts "Wrote #{OUTPUT.relative_path_from(ROOT)}"
